---
title: "code"
output: html_document
---


```{r}
script.start <- Sys.time()
cat("Beginning model script\n")

cat("Loading packages\n")
library(sp)
library(rgeos)
library(dplyr)
library(tidyr)
library(sf)
library(spdep)
library(CARBayes)

cat("Creating blockgroup demographic dataframe\n")
# read in blockgroup demographic and provider data
dem <- read.csv('data/us-dem-counts-jan-2021.csv', header=TRUE, colClasses=c("spatial_id"="character"))

# select columns needed for model
dem <- dem %>% dplyr::select(spatial_id, BlackNotHispPercent, HispanicPercent, NativePercent, Population, NumProviders)

# note - some blockgroups are missing population data, we're waiting for update
# from Simply Analytics - we drop values for now
dem <- na.omit(dem)

# scale independent variables but not offset
dem <- dem %>% mutate_at(c("BlackNotHispPercent", "HispanicPercent", "NativePercent"), ~(scale(.) %>% as.vector))

```

```{r}
cat("Creating blockgroup spatial dataframe\n")
geom.start <- Sys.time()

# read blockgroup geodata into sf dataframe
geom.sf <- st_read('data/us-test-sites-nov-2020.shp')

# add state column to facilitate state-by-state analysis
geom.sf <- geom.sf %>% separate(name, c("first", "second", "state"), sep = ",", remove=FALSE) %>% dplyr::select(-first, -second)

# trim whitespace
geom.sf$state <- trimws(geom.sf$state)

# subset small state for testing
state = 'RI'
cat("Testing on state", state)
geom.sf <- geom.sf %>% filter(state == state)

# convert to spatial polygons dataframe
geom.sp <- as(geom.sf, "Spatial")

# drop blockgroups with missing pop
geom.sp <- geom.sp[geom.sp$spatial_id %in% dem$spatial_id, ]
geom.end <- Sys.time()
cat("Time to build spatial dataframe: ", geom.end - geom.start, "\n")
```

```{r}
# create neighbors list
neighbors.start <- Sys.time()
file_path <- paste("data/neighbors_matrix_", state, ".rds", sep='')
if (file.exists(file_path)) {
  cat("Loading saved neighbors list\n")
  neighbors <- readRDS(file_path)
  
  if (length(neighbors) != length(geom.sp)) {
    cat("Saved neighbors list incorrect size - rebuilding\n")
    neighbors <- poly2nb(geom.sp, queen = TRUE, snap = 0)
    saveRDS(neighbors, file=file_path)
    neighbors.end <- Sys.time()
    cat("Time to build neighbors list: ", neighbors.end - neighbors.start, "\n")
  }
  
} else {
    cat("Building neighbors list\n")
    neighbors <- poly2nb(geom.sp, queen = TRUE, snap = 0)
    saveRDS(neighbors, file=file_path)
    neighbors.end <- Sys.time()
    cat("Time to build neighbors list: ", neighbors.end - neighbors.start, "\n")
}
```

```{r}
# create neighbors matrix
neighbors_mat.start = Sys.time()
file_path = paste("data/neighbors_matrix_", state, ".rds", sep='')
if (file.exists(file_path)) {
  cat("Loading saved neighbors matrix\n")
  neighbors_mat <- readRDS(file_path)
  
  if (length(neighbors_mat) != length(neighbors)) {
    cat("Saved neighbors matrix incorrect size - rebuilding\n")
    neighbors_mat <- nb2mat(neighbors, zero.policy = TRUE, style = "B")
    saveRDS(neighbors, file="data/neighbors_matrix.rds")
    neighbors_mat.end <- Sys.time()
    cat("Time to build neighbors matrix: ", neighbors_mat.end - neighbors_mat.start, "\n")
  }
  
} else {
    cat("Building neighbors matrix\n")
    neighbors_mat <- nb2mat(neighbors, zero.policy = TRUE, style = "B")
    saveRDS(neighbors_mat, file=file_path)
    neighbors_mat.end <- Sys.time()
    cat("Time to build neighbors matrix: ", neighbors_mat.end - neighbors_mat.start, "\n")
}
```

```{r}
# run model
model.start = Sys.time()
file_path = paste("data/model_", state, ".rds", sep='')
if (file.exists(file_path)) {
  print("Loading saved model\n")
  model <- readRDS(file_path)
  
  if (length(ns$fitted.values) != length(neighbors_mat)) {
    print("Saved model incorrect size - refitting\n")
    model <- S.CARleroux(formula = NumProviders ~ BlackNotHispPercent + HispanicPercent + NativePercent + offset(log(Population + 1)), 
                  data = dem, family = "poisson", burnin = 100000, n.sample = 1100000, thin = 100, W = neighbors_mat, 
                  prior.mean.beta = rep(0, times = 4), prior.var.beta = rep(100^2, times = 4), prior.tau2 = c(0.01, 0.01))
    saveRDS(model, file=file_path)
    model.end <- Sys.time()
    cat("Time to fit model: ", model.end - model.start, "\n")
  }
  
} else {
    model <- S.CARleroux(formula = NumProviders ~ BlackNotHispPercent + HispanicPercent + NativePercent + offset(log(Population + 1)), 
                  data = dem, family = "poisson", burnin = 100000, n.sample = 1100000, thin = 100, W = neighbors_mat, 
                  prior.mean.beta = rep(0, times = 4), prior.var.beta = rep(100^2, times = 4), prior.tau2 = c(0.01, 0.01))
    saveRDS(model, file=file_path)
    model.end <- Sys.time()
    cat("Time to fit model: ", model.end - model.start, "\n")
}

print("Model Summary\n")
# print model summary
print(model)

# print script total run time
script.end <- Sys.time()
cat("Script complete - total elapsed time: ", script.end - script.start, "\n")
```